print("Hello World! This is my first programming program :]")
print ()
print ("        HH      HH   II   !!!") 
print ("        HH      HH        !!!") 
print ("        HH      HH   II   !!!") 
print ("        HHHHHHHHHH   II   !!!")
print ("        HH      HH   II   !!!")
print ("        HH      HH   II   !!!")
print ("        HH      HH   II    !")
print ()
print ("          Date: 10 - 7 - 2024")

